import { tw } from "./tw.js";

const darkMode = false;
const grayVariant = ts.Neutral;

const shadowScale = darkMode
	? [950, 900, 800, 700, 600, 500, 400, 300, 200, 100, 50]
	: [50, 100, 200, 300, 400, 500, 600, 700, 800, 900, 950];

const transparent = transparent;

const json = {
	"name": "simplest",
	"colors": {
		"focusBorder": tw.Indigo[shadowScale[5]],
		"foreground": grayVariant[shadowScale[8]],
		"disabledForeground": grayVariant[shadowScale[7]],
		"widget.border": grayVariant[shadowScale[5]],
		"widget.shadow": grayVariant[shadowScale[5]],
		"selection.background": grayVariant[shadowScale[3]],
		"descriptionForeground": grayVariant[shadowScale[8]],
		"errorForeground": tw.Red[shadowScale[6]],
		"icon.foreground": grayVariant[shadowScale[8]],
		"sash.hoverBorder": grayVariant[shadowScale[5]],
		"window.activeBorder": grayVariant[shadowScale[1]],
		"textBlockQuote.background": grayVariant[shadowScale[2]],
		"textBlockQuote.border": grayVariant[shadowScale[4]],
		"textCodeBlock.background": grayVariant[shadowScale[0]],
		"textLink.activeForeground": tw.Blue[shadowScale[10]],
		"textLink.foreground": tw.Blue[shadowScale[7]],
		"textPreformat.foreground": grayVariant[shadowScale[8]],
		"textSeparator.foreground": grayVariant[shadowScale[8]],
		"toolbar.hoverBackground": grayVariant[shadowScale[1]],
		"toolbar.hoverOutline": grayVariant[shadowScale[1]],
		"toolbar.activeBackground": grayVariant[shadowScale[1]],
		"button.background": tw.Indigo[shadowScale[5]],
		"button.foreground": grayVariant[shadowScale[0]],
		"button.border": transparent,
		"button.separator": grayVariant[shadowScale[0]],
		"button.hoverBackground": tw.Indigo[shadowScale[7]],
		"button.secondaryForeground": grayVariant[shadowScale[10]],
		"button.secondaryBackground": grayVariant[shadowScale[5]],
		"button.secondaryHoverBackground": grayVariant[shadowScale[5]],
		"checkbox.background": grayVariant[shadowScale[1]],
		"checkbox.foreground": grayVariant[shadowScale[7]],
		"checkbox.border": grayVariant[shadowScale[7]],
		"checkbox.selectBackground": grayVariant[shadowScale[7]],
		"checkbox.selectBorder": grayVariant[shadowScale[1]],
		"dropdown.background": grayVariant[shadowScale[2]],
		"dropdown.listBackground": grayVariant[shadowScale[2]],
		"dropdown.border": grayVariant[shadowScale[2]],
		"dropdown.foreground": grayVariant[shadowScale[10]],
		"input.background": grayVariant[shadowScale[0]],
		"input.border": grayVariant[shadowScale[1]],
		"input.foreground": grayVariant[shadowScale[8]],
		"input.placeholderForeground": grayVariant[shadowScale[5]],
		"inputValidation.errorBackground": tw.Red[shadowScale[1]],
		"inputValidation.errorForeground": tw.Red[shadowScale[6]],
		"inputValidation.errorBorder": tw.Red[shadowScale[2]],
		"inputValidation.infoBackground": tw.Blue[shadowScale[1]],
		"inputValidation.infoForeground": tw.Blue[shadowScale[6]],
		"inputValidation.infoBorder": tw.Blue[shadowScale[2]],
		"inputValidation.warningBackground": tw.Orange[shadowScale[1]],
		"inputValidation.warningForeground": tw.Orange[shadowScale[6]],
		"inputValidation.warningBorder": tw.Orange[shadowScale[2]],
		"scrollbar.shadow": transparent,
		"scrollbarSlider.activeBackground": grayVariant[shadowScale[3]],
		"scrollbarSlider.background": grayVariant[shadowScale[2]],
		"scrollbarSlider.hoverBackground": grayVariant[shadowScale[3]],
		"badge.foreground": grayVariant[shadowScale[0]],
		"badge.background": grayVariant[shadowScale[8]],
		"progressBar.background": grayVariant[shadowScale[8]],
		"list.activeSelectionBackground": grayVariant[shadowScale[3]],
		"list.activeSelectionForeground": grayVariant[shadowScale[9]],
		"list.activeSelectionIconForeground": grayVariant[shadowScale[9]],
		"list.dropBackground": grayVariant[shadowScale[4]],
		"list.focusBackground": grayVariant[shadowScale[3]],
		"list.focusForeground": grayVariant[shadowScale[9]],
		"list.focusHighlightForeground": grayVariant[shadowScale[9]],
		"list.focusOutline": transparent,
		"list.focusAndSelectionOutline": transparent,
		"list.highlightForeground": tw.Indigo[shadowScale[7]],
		"list.hoverBackground": grayVariant[shadowScale[3]],
		"list.hoverForeground": grayVariant[shadowScale[8]],
		"list.invalidItemForeground": tw.Red[shadowScale[6]],
		"list.errorForeground": tw.Red[shadowScale[6]],
		"list.warningForeground": tw.Orange[shadowScale[6]],
		"activityBar.background": grayVariant[shadowScale[1]],
		"activityBar.dropBorder": grayVariant[shadowScale[3]],
		"activityBar.foreground": grayVariant[shadowScale[8]],
		"activityBar.inactiveForeground": grayVariant[shadowScale[4]],
		"activityBar.border": grayVariant[shadowScale[1]],
		"activityBarBadge.background": tw.Indigo[shadowScale[5]],
		"activityBarBadge.foreground": grayVariant[shadowScale[0]],
		"activityBar.activeBorder": grayVariant[shadowScale[8]],
		"activityBar.activeBackground": grayVariant[shadowScale[1]],
		"activityBar.activeFocusBorder": grayVariant[shadowScale[8]],
		"sideBar.background": grayVariant[shadowScale[1]],
		"sideBar.foreground": grayVariant[shadowScale[6]],
		"sideBar.border": transparent,
		"sideBar.dropBackground": grayVariant[shadowScale[6]],
		"sideBarTitle.foreground": grayVariant[shadowScale[8]],
		"sideBarSectionHeader.background": grayVariant[shadowScale[2]],
		"sideBarSectionHeader.foreground": grayVariant[shadowScale[8]],
		"sideBarSectionHeader.border": transparent,
		"editorGroup.border": transparent,
		"editorGroup.dropBackground": grayVariant[shadowScale[2]],
		"editorGroupHeader.noTabsBackground": grayVariant[shadowScale[3]],
		"editorGroupHeader.tabsBackground": grayVariant[shadowScale[1]],
		"editorGroupHeader.tabsBorder": transparent,
		"editorGroupHeader.border": transparent,
		"editorGroup.emptyBackground": grayVariant[shadowScale[2]],
		"editorGroup.focusedEmptyBorder": grayVariant[shadowScale[2]],
		"editorGroup.dropIntoPromptForeground": grayVariant[shadowScale[7]],
		"editorGroup.dropIntoPromptBackground": grayVariant[shadowScale[1]],
		"editorGroup.dropIntoPromptBorder": transparent,
		"tab.unfocusedActiveBackground": grayVariant[shadowScale[0]],
		"tab.activeForeground": grayVariant[shadowScale[9]],
		"tab.border": transparent,
		"tab.activeBorder": transparent,
		"tab.unfocusedActiveBorder": transparent,
		"tab.activeBorderTop": transparent,
		"tab.unfocusedActiveBorderTop": transparent,
		"tab.lastPinnedBorder": transparent,
		"tab.inactiveBackground": grayVariant[shadowScale[2]],
		"tab.unfocusedInactiveBackground": grayVariant[shadowScale[2]],
		"tab.inactiveForeground": grayVariant[shadowScale[6]],
		"tab.unfocusedActiveForeground": grayVariant[shadowScale[9]],
		"tab.unfocusedInactiveForeground": grayVariant[shadowScale[6]],
		"tab.hoverBackground": grayVariant[shadowScale[0]],
		"tab.unfocusedHoverBackground": grayVariant[shadowScale[0]],
		"tab.hoverForeground": grayVariant[shadowScale[9]],
		"tab.unfocusedHoverForeground": grayVariant[shadowScale[9]],
		"tab.hoverBorder": transparent,
		"tab.unfocusedHoverBorder": transparent,
		"tab.activeModifiedBorder": tw.Indigo[shadowScale[5]],
		"tab.inactiveModifiedBorder": tw.Indigo[shadowScale[5]],
		"tab.unfocusedActiveModifiedBorder": tw.Indigo[shadowScale[5]],
		"tab.unfocusedInactiveModifiedBorder": tw.Indigo[shadowScale[5]],
		"editorPane.background": grayVariant[shadowScale[1]],
		"sideBySideEditor.horizontalBorder": grayVariant[shadowScale[1]],
		"sideBySideEditor.verticalBorder": grayVariant[shadowScale[1]],
		"editor.background": grayVariant[shadowScale[0]],
		"editor.foreground": grayVariant[shadowScale[8]],
		"editorLineNumber.foreground": grayVariant[shadowScale[4]],
		"editorLineNumber.activeForeground": grayVariant[shadowScale[6]],
		"editorLineNumber.dimmedForeground": grayVariant[shadowScale[6]],
		"editorCursor.background": grayVariant[shadowScale[0]],
		"editorCursor.foreground": tw.Indigo[shadowScale[5]],
		"editor.selectionBackground": grayVariant[shadowScale[3]],
		"editor.selectionForeground": grayVariant[shadowScale[10]],
		"editor.inactiveSelectionBackground": grayVariant[shadowScale[2]],
		"editor.selectionHighlightBackground": tw.Yellow[shadowScale[0]],
		"editor.selectionHighlightBorder": transparent,
		"editor.wordHighlightBackground": tw.Yellow[shadowScale[2]],
		"editor.wordHighlightBorder": transparent,
		"editor.wordHighlightStrongBackground": tw.Yellow[shadowScale[2]],
		"editor.wordHighlightStrongBorder": transparent,
		"editor.findMatchBackground": tw.Yellow[shadowScale[2]],
		"editor.findMatchHighlightBackground": tw.Yellow[shadowScale[1]],
		"editor.findRangeHighlightBackground": tw.Yellow[shadowScale[2]],
		"editor.findMatchBorder": transparent,
		"editor.findMatchHighlightBorder": transparent,
		"editor.findRangeHighlightBorder": transparent,
		"editor.hoverHighlightBackground": tw.Yellow[shadowScale[1]],
		"editorLink.activeForeground": tw.Blue[shadowScale[5]],
		"editorWhitespace.foreground": grayVariant[shadowScale[2]],
		"editorIndentGuide.background": grayVariant[shadowScale[3]],
		"editorIndentGuide.activeBackground": grayVariant[shadowScale[5]],
		"editorRuler.foreground": grayVariant[shadowScale[2]],
		"editorBracketMatch.background": grayVariant[shadowScale[3]],
		"editorBracketMatch.border": transparent,
		"editorBracketHighlight.foreground1": tw.Indigo[shadowScale[4]],
		"editorBracketHighlight.foreground2": tw.Violet[shadowScale[4]],
		"editorBracketHighlight.foreground3": tw.Purple[shadowScale[4]],
		"editorBracketHighlight.foreground4": tw.Fuchsia[shadowScale[4]],
		"editorBracketHighlight.foreground5": tw.Pink[shadowScale[4]],
		"editorBracketHighlight.foreground6": tw.Rose[shadowScale[4]],
		"editorBracketHighlight.unexpectedBracket.foreground": tw.Yellow[shadowScale[5]],
		"editorBracketPairGuide.activeBackground1": tw.Indigo[shadowScale[4]],
		"editorBracketPairGuide.activeBackground2": tw.Violet[shadowScale[4]],
		"editorBracketPairGuide.activeBackground3": tw.Purple[shadowScale[4]],
		"editorBracketPairGuide.activeBackground4": tw.Fuchsia[shadowScale[4]],
		"editorBracketPairGuide.activeBackground5": tw.Pink[shadowScale[4]],
		"editorBracketPairGuide.activeBackground6": tw.Rose[shadowScale[4]],
		"editorBracketPairGuide.background1": tw.Indigo[shadowScale[3]],
		"editorBracketPairGuide.background2": tw.Violet[shadowScale[3]],
		"editorBracketPairGuide.background3": tw.Purple[shadowScale[3]],
		"editorBracketPairGuide.background4": tw.Fuchsia[shadowScale[3]],
		"editorBracketPairGuide.background5": tw.Pink[shadowScale[3]],
		"editorBracketPairGuide.background6": tw.Rose[shadowScale[3]],
		"editor.foldBackground": grayVariant[shadowScale[2]],
		"editorOverviewRuler.border": transparent,
		"editorOverviewRuler.modifiedForeground": tw.Amber[shadowScale[5]],
		"editorOverviewRuler.addedForeground": tw.Emerald[shadowScale[5]],
		"editorOverviewRuler.deletedForeground": tw.Rose[shadowScale[5]],
		"editorOverviewRuler.errorForeground": tw.Red[shadowScale[5]],
		"editorOverviewRuler.warningForeground": tw.Orange[shadowScale[5]],
		"editorOverviewRuler.infoForeground": tw.Blue[shadowScale[5]],
		"editorOverviewRuler.bracketMatchForeground": grayVariant[shadowScale[7]],
		"editorError.foreground": tw.Red[shadowScale[6]],
		"editorError.border": tw.Red[shadowScale[2]],
		"editorError.background": tw.Red[shadowScale[2]],
		"editorWarning.foreground": tw.Orange[shadowScale[6]],
		"editorWarning.border": tw.Orange[shadowScale[2]],
		"editorWarning.background": tw.Orange[shadowScale[2]],
		"editorInfo.foreground": tw.Blue[shadowScale[6]],
		"editorInfo.border": tw.Blue[shadowScale[2]],
		"editorInfo.background": tw.Blue[shadowScale[2]],
		"editorHint.foreground": tw.Cyan[shadowScale[7]],
		"editorHint.border": tw.Cyan[shadowScale[2]],
		"problemsErrorIcon.foreground": tw.Red[shadowScale[6]],
		"problemsWarningIcon.foreground": tw.Orange[shadowScale[6]],
		"problemsInfoIcon.foreground": tw.Blue[shadowScale[6]],
		"editorUnnecessaryCode.border": tw.Red[shadowScale[6]],
		"editorGutter.modifiedBackground": tw.Amber[shadowScale[5]],
		"editorGutter.addedBackground": tw.Emerald[shadowScale[5]],
		"editorGutter.deletedBackground": tw.Rose[shadowScale[5]],
		"editorGutter.foldingControlForeground": grayVariant[shadowScale[6]],
		"diffEditor.insertedTextBackground": tw.Emerald[shadowScale[2]],
		"diffEditor.insertedTextBorder": transparent,
		"diffEditor.removedTextBackground": tw.Rose[shadowScale[2]],
		"diffEditor.removedTextBorder": transparent,
		"diffEditor.border": grayVariant[shadowScale[3]],
		"diffEditor.diagonalFill": tw.Yellow[shadowScale[2]],
		"diffEditor.insertedLineBackground": tw.Emerald[shadowScale[2]],
		"diffEditor.removedLineBackground": tw.Rose[shadowScale[2]],
		"diffEditorGutter.insertedLineBackground": tw.Emerald[shadowScale[2]],
		"diffEditorGutter.removedLineBackground": tw.Rose[shadowScale[2]],
		"diffEditorOverview.insertedForeground": tw.Emerald[shadowScale[5]],
		"diffEditorOverview.removedForeground": tw.Rose[shadowScale[5]],
		"editorWidget.foreground": grayVariant[shadowScale[8]],
		"editorWidget.background": grayVariant[shadowScale[1]],
		"editorWidget.border": transparent,
		"editorWidget.resizeBorder": transparent,
		"editorSuggestWidget.background": grayVariant[shadowScale[1]],
		"editorSuggestWidget.border": transparent,
		"editorSuggestWidget.foreground": grayVariant[shadowScale[8]],
		"editorSuggestWidget.focusHighlightForeground": grayVariant[shadowScale[8]],
		"editorSuggestWidget.highlightForeground": grayVariant[shadowScale[10]],
		"editorSuggestWidget.selectedBackground": grayVariant[shadowScale[2]],
		"editorSuggestWidget.selectedForeground": grayVariant[shadowScale[10]],
		"editorSuggestWidgetStatus.foreground": grayVariant[shadowScale[10]],
		"editorHoverWidget.background": grayVariant[shadowScale[2]],
		"editorHoverWidget.border": transparent,
		"editorHoverWidget.highlightForeground": grayVariant[shadowScale[3]],
		"editorHoverWidget.statusBarBackground": grayVariant[shadowScale[3]],
		"editorGhostText.border": transparent,
		"editorGhostText.foreground": grayVariant[shadowScale[5]],
		"editorStickyScrollHover.background": grayVariant[shadowScale[1]],
		"panel.background": grayVariant[shadowScale[1]],
		"panel.border": transparent,
		"panel.dropBorder": grayVariant[shadowScale[2]],
		"panelTitle.activeBorder": grayVariant[shadowScale[10]],
		"panelTitle.activeForeground": grayVariant[shadowScale[10]],
		"panelTitle.inactiveForeground": grayVariant[shadowScale[6]],
		"panelInput.border": transparent,
		"panelSection.border": transparent,
		"panelSection.dropBackground": grayVariant[shadowScale[2]],
		"statusBar.background": grayVariant[shadowScale[1]],
		"statusBar.foreground": grayVariant[shadowScale[8]],
		"statusBar.border": transparent,
		"statusBar.debuggingBackground": grayVariant[shadowScale[2]],
		"statusBar.debuggingForeground": grayVariant[shadowScale[9]],
		"statusBar.debuggingBorder": transparent,
		"statusBar.noFolderForeground": grayVariant[shadowScale[8]],
		"statusBar.noFolderBackground": grayVariant[shadowScale[0]],
		"statusBar.noFolderBorder": transparent,
		"statusBarItem.activeBackground": grayVariant[shadowScale[2]],
		"statusBarItem.hoverBackground": grayVariant[shadowScale[2]],
		"statusBarItem.prominentForeground": grayVariant[shadowScale[2]],
		"statusBarItem.prominentBackground": grayVariant[shadowScale[9]],
		"statusBarItem.prominentHoverBackground": grayVariant[shadowScale[3]],
		"statusBarItem.remoteBackground": tw.Indigo[shadowScale[5]],
		"statusBarItem.remoteForeground": grayVariant[shadowScale[10]],
		"statusBarItem.errorBackground": tw.Red[shadowScale[5]],
		"statusBarItem.errorForeground": grayVariant[shadowScale[10]],
		"statusBarItem.warningBackground": tw.Orange[shadowScale[5]],
		"statusBarItem.warningForeground": grayVariant[shadowScale[10]],
		"statusBarItem.focusBorder": transparent,
		"statusBar.focusBorder": transparent,
		"titleBar.activeBackground": grayVariant[shadowScale[1]],
		"titleBar.activeForeground": grayVariant[shadowScale[8]],
		"titleBar.inactiveBackground": grayVariant[shadowScale[1]],
		"titleBar.inactiveForeground": grayVariant[shadowScale[5]],
		"titleBar.border": transparent,
		"pickerGroup.border": transparent,
		"pickerGroup.foreground": grayVariant[shadowScale[8]],
		"quickInput.background": grayVariant[shadowScale[1]],
		"quickInput.foreground": grayVariant[shadowScale[8]],
		"quickInputList.focusBackground": grayVariant[shadowScale[3]],
		"quickInputList.focusForeground": grayVariant[shadowScale[10]],
		"quickInputTitle.background": grayVariant[shadowScale[1]],
		"terminal.background": grayVariant[shadowScale[1]],
		"terminal.border": transparent,
		"terminal.foreground": grayVariant[shadowScale[10]],
		"terminal.ansiBlack": grayVariant[shadowScale[9]],
		"terminal.ansiBrightBlack": grayVariant[shadowScale[7]],
		"terminal.ansiRed": tw.Red[shadowScale[6]],
		"terminal.ansiBrightRed": tw.Red[shadowScale[5]],
		"terminal.ansiGreen": tw.Green[shadowScale[6]],
		"terminal.ansiBrightGreen": tw.Green[shadowScale[5]],
		"terminal.ansiYellow": tw.Yellow[shadowScale[5]],
		"terminal.ansiBrightYellow": tw.Yellow[shadowScale[4]],
		"terminal.ansiBlue": tw.Blue[shadowScale[6]],
		"terminal.ansiBrightBlue": tw.Blue[shadowScale[5]],
		"terminal.ansiBrightMagenta": tw.Fuchsia[shadowScale[5]],
		"terminal.ansiMagenta": tw.Fuchsia[shadowScale[6]],
		"terminal.ansiCyan": tw.Cyan[shadowScale[6]],
		"terminal.ansiBrightCyan": tw.Cyan[shadowScale[5]],
		"terminal.ansiWhite": grayVariant[shadowScale[6]],
		"terminal.ansiBrightWhite": grayVariant[shadowScale[4]],
		"terminal.selectionBackground": grayVariant[shadowScale[4]],
		"terminal.inactiveSelectionBackground": grayVariant[shadowScale[3]],
		"terminalCursor.foreground": tw.Indigo[shadowScale[5]],
		"terminal.dropBackground": grayVariant[shadowScale[4]],
		"terminal.tab.activeBorder": tw.Indigo[shadowScale[5]],
		"terminalCommandDecoration.defaultBackground": grayVariant[shadowScale[5]],
		"terminalCommandDecoration.successBackground": tw.Green[shadowScale[5]],
		"terminalCommandDecoration.errorBackground": tw.Red[shadowScale[5]],
		"testing.iconFailed": tw.Red[shadowScale[5]],
		"testing.iconErrored": tw.Orange[shadowScale[5]],
		"testing.iconPassed": tw.Green[shadowScale[5]],
		"testing.runAction": tw.Green[shadowScale[5]],
		"testing.iconQueued": tw.Teal[shadowScale[5]],
		"testing.iconUnset": grayVariant[shadowScale[5]],
		"testing.iconSkipped": tw.Yellow[shadowScale[5]],
		"testing.message.error.decorationForeground": tw.Red[shadowScale[5]],
		"testing.message.error.lineBackground": tw.Red[shadowScale[1]],
		"testing.message.info.decorationForeground": tw.Sky[shadowScale[5]],
		"testing.message.info.lineBackground": tw.Sky[shadowScale[1]],
		"gitDecoration.addedResourceForeground": tw.Emerald[shadowScale[5]],
		"gitDecoration.modifiedResourceForeground": tw.Amber[shadowScale[5]],
		"gitDecoration.deletedResourceForeground": tw.Rose[shadowScale[5]],
		"gitDecoration.renamedResourceForeground": tw.Amber[shadowScale[5]],
		"gitDecoration.stageModifiedResourceForeground": tw.Emerald[shadowScale[6]],
		"gitDecoration.stageDeletedResourceForeground": tw.Rose[shadowScale[6]],
		"gitDecoration.untrackedResourceForeground": tw.Amber[shadowScale[4]],
		"gitDecoration.ignoredResourceForeground": grayVariant[shadowScale[5]],
		"gitDecoration.conflictingResourceForeground": tw.Red[shadowScale[4]],
		"gitDecoration.submoduleResourceForeground": tw.Pink[shadowScale[5]],
		"charts.red": tw.Red[shadowScale[5]],
		"charts.blue": tw.Blue[shadowScale[5]],
		"charts.yellow": tw.Yellow[shadowScale[5]],
		"charts.orange": tw.Orange[shadowScale[5]],
		"charts.green": tw.Green[shadowScale[5]],
		"charts.purple": tw.Purple[shadowScale[5]],
	},
	"tokenColors": [
		{
			"scope": [
				"string",
				"constant.numeric",
				"constant.character",
				"constant.other",
				"punctuation.definition.string",
			],
			"settings": {
				"foreground": tw.Green[shadowScale[7]]
			}
		},
		{
			"scope": [
				"keyword",
				"keyword.operator.new",
				"storage.modifier",
				"storage.type",
				"constant.language",
				"support.type",
				"support.type.property-name.json"
			],
			"settings": {
				"foreground": tw.Blue[shadowScale[7]]
			}
		},
		{
			"scope": [
				"meta",
				"support.type",
				"variable.other.readwrite.alias",
			],
			"settings": {
				"foreground": tw.Purple[shadowScale[7]]
			}
		},
		{
			"scope": [
				"variable"
			],
			"settings": {
				"foreground": grayVariant[shadowScale[9]]
			}
		},
		{
			"scope": [
				"variable.other.constant"
			],
			"settings": {
				"fontStyle": "italic"
			}
		},
		{
			"scope": [
				"comment",
				"punctuation",
				"meta.brace",
				"storage.type.function.arrow"
			],
			"settings": {
				"foreground": grayVariant[shadowScale[5]]
			}
		},
	]
}
